--
-- Volcado de datos para la tabla `equipos`
--

INSERT INTO `equipos` (`id`, `nombre`, `escudo`) VALUES
(1, 'Real Madrid CF', ''),
(2, 'FC Barcelona', ''),
(3, 'Valencia CF', ''),
(4, 'Atlético Madrid', ''),
(5, 'Athletic Club', ''),
(6, 'RCD Espanyol', ''),
(7, 'Sevilla FC', ''),
(8, 'Real Sociedad', ''),
(9, 'Real Zaragoza', ''),
(10, 'Real Betis', ''),
(11, 'RC Deportivo', ''),
(12, 'RC Celta de Vigo', ''),
(13, 'Real Valladolid', ''),
(14, 'Real Racing Club', ''),
(15, 'CA Osasuna', ''),
(16, 'Real S. de Gijón', ''),
(17, 'Real Oviedo C.F.', ''),
(18, 'R.C.D. Mallorca', ''),
(19, 'U.D. Las Palmas', ''),
(20, 'Villarreal CF', ''),
(21, 'Málaga CF', ''),
(22, 'Rayo Vallecano', ''),
(23, 'Granada CF', ''),
(24, 'Elche CF', ''),
(25, 'C.D. Málaga', ''),
(26, 'Hércules C.F.', ''),
(27, 'C.D. Tenerife', ''),
(28, 'Getafe CF', ''),
(29, 'Real Murcia C.F.', ''),
(30, 'U.D. Salamanca', ''),
(31, 'Levante UD', ''),
(32, 'C.D. Alavés', ''),
(33, 'C.D. Sabadell', ''),
(34, 'Cádiz C.F.', ''),
(35, 'C.D. Logroñés', ''),
(36, 'C.D. Castellón', ''),
(37, 'Albacete Balomp.', ''),
(38, 'UD Almería', ''),
(39, 'Córdoba CF', ''),
(40, 'S.D. Compostela', ''),
(41, 'R.C.R. de Huelva', ''),
(42, 'Burgos C.F.', ''),
(43, 'Pontevedra C.F.', ''),
(44, 'C.D. Numancia', ''),
(45, 'Arenas de Guecho', ''),
(46, 'Real Burgos C.F.', ''),
(47, 'Club Gimnàstic', ''),
(48, 'C.F. Extremadura', ''),
(49, 'Mérida C.P.', ''),
(50, 'C.D. Alcoyano', ''),
(51, 'Real Jaén C.F.', ''),
(52, 'Real Unión Club', ''),
(53, 'AD Almería', ''),
(54, 'C.D. Europa', ''),
(55, 'U.E. Lleida', ''),
(56, 'Xerez C.D.', ''),
(57, 'SD Eibar', ''),
(58, 'Condal', ''),
(59, 'At. Tetuan', ''),
(60, 'C. y D. Leonesa', '');
